### ISSUE TITLE
@imports with tildes are not matched to the node_modules folder

### ISSUE THREAD

**Issue by RyKilleen** [Platypi/less-bundle#2]
Importing from node_modules has become a common pattern, and looks like the following:

`@import ~@organization/package/components/component/styles/styles.less`

Currently, `less-bundle` takes the path literally.

`c:\project\styles\~@organization/package/components/component/styles/styles.less`

It'd be great if this package could support substituting `node_modules` in when appropriate! I'll be submitting a PR shortly that should address the issue.

**Comment by RyKilleen** [comment]
Also if this isn't under any development and you'd prefer we fork @m-s-morgan, happy to go that route. Not sure who to ping on it.

**Comment by RyKilleen** [comment]
@m-s-morgan is there a chance this could be npm published in the short-term?

**Comment by ChocolateLoverRaj** [comment]
Yes is there anyone who has forked this and published to npm with node modules support?
